version: "3"
services:
  csharp: #docker run -it -v ${PWD}:/work -w /work -p 5000:5000 aortizpalma/csharp:1.0.0 /bin/sh
    container_name: csharp
    image: aortizpalma/csharp:1.0.0
    build: ./c#
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./c#/src/:/work
    ports:
      - 5000:5000
  golang: #docker run -it -v ${PWD}:/work -w /work -p 5001:5000 aortizpalma/golang:1.0.0 /bin/sh
    container_name: golang
    image: aortizpalma/golang:1.0.0
    build: ./golang
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./golang/src/:/work
    ports:
      - 5001:5000
  nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 aortizpalma/nodejs:1.0.0 /bin/sh
    container_name: nodejs
    image: aortizpalma/nodejs:1.0.0
    build: ./nodejs
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./nodejs/src/:/work
    ports:
      - 5002:5000
  python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 aortizpalma/python:1.0.0 /bin/sh
    container_name: python
    image: aortizpalma/python:1.0.0
    build: ./python
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./python/src/:/work
    ports:
      - 5003:5000
